/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatDarculaLaf;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Produtos;
import model.dao.ProdutoDAO;

/**
 *
 * @author 232.933573
 */
public final class GerenciarProdutos extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form AdicionarProduto
     */
    public GerenciarProdutos() {
        
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) JtProdutos.getModel();
        JtProdutos.setRowSorter(new TableRowSorter(modelo));
        
        readJtable();
        
        
//        
//        readJtable();
//         
//        SwingUtilities.invokeLater(() -> {
//        
//            try {
//                UIManager.setLookAndFeel(new FlatDarculaLaf());
//                SwingUtilities.updateComponentTreeUI(this);
//            } catch (UnsupportedLookAndFeelException ex) {
//                Logger.getLogger(GerenciarProdutos.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        
//        });
    }

    public void readJtable(){
        
        DefaultTableModel modelo = (DefaultTableModel) JtProdutos.getModel();
//        modelo.setNumRows(0);
        ProdutoDAO pdao = new ProdutoDAO();
        
        for(Produtos p: pdao.read()){
            
            modelo.addRow(new Object[]{
                
                p.getId_produtos(),
                p.getNomeProdutos(),
                p.getQuantidade(),
                p.getPreco()
            
            });
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomedoProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtProdutos = new javax.swing.JTable();
        BotaoAdicionarProduto = new javax.swing.JButton();
        BotaoRemoverProduto = new javax.swing.JButton();
        BotaoAlterarProduto = new javax.swing.JButton();
        BotaoSalvarTabela = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setClosable(true);
        setForeground(java.awt.Color.white);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nome do Produto");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Quantidade");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Preço");

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        JtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Quantidade", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JtProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtProdutosMouseClicked(evt);
            }
        });
        JtProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtProdutosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(JtProdutos);

        BotaoAdicionarProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotaoAdicionarProduto.setText("Adicionar Produto");
        BotaoAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAdicionarProdutoActionPerformed(evt);
            }
        });

        BotaoRemoverProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotaoRemoverProduto.setText("Remover Produto");
        BotaoRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRemoverProdutoActionPerformed(evt);
            }
        });

        BotaoAlterarProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotaoAlterarProduto.setText("Alterar Produto");
        BotaoAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAlterarProdutoActionPerformed(evt);
            }
        });

        BotaoSalvarTabela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotaoSalvarTabela.setText("Salvar");
        BotaoSalvarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarTabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNomedoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BotaoAlterarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(BotaoAdicionarProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(BotaoRemoverProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(BotaoSalvarTabela)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomedoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(BotaoAdicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(BotaoRemoverProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(BotaoAlterarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoSalvarTabela)))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void BotaoAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAdicionarProdutoActionPerformed
      
        Produtos p  = new Produtos();
        ProdutoDAO dao = new ProdutoDAO();
        p.setNomeProdutos(txtNomedoProduto.getText());
        p.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
        p.setPreco(Double.parseDouble(txtPreco.getText()));
        dao.create(p);
      
      DefaultTableModel Produtos = (DefaultTableModel) JtProdutos.getModel();
      Object[] dados = {p.getId_produtos()  , txtNomedoProduto.getText(), txtQuantidade.getText(), txtPreco.getText()};
      Produtos.addRow(dados);
        
        
      txtNomedoProduto.setText("");
      txtQuantidade.setText("");
      txtPreco.setText("");
        
       readJtable(); 
    
        
    }//GEN-LAST:event_BotaoAdicionarProdutoActionPerformed

    private void BotaoRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRemoverProdutoActionPerformed
        
        if (JtProdutos.getSelectedRow() != -1){
            DefaultTableModel Produtos = (DefaultTableModel) JtProdutos.getModel();
            Produtos.removeRow(JtProdutos.getSelectedRow());
        }
        else{
            JOptionPane.showMessageDialog(null, "Produto não selecionado");
        }
        
        txtNomedoProduto.setText("");
        txtQuantidade.setText("");
        txtPreco.setText("");
        
    }//GEN-LAST:event_BotaoRemoverProdutoActionPerformed

    private void JtProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtProdutosMouseClicked

        if(JtProdutos.getSelectedRow() != -1){
            txtNomedoProduto.setText(JtProdutos.getValueAt(JtProdutos.getSelectedRow(), 1).toString());
            txtQuantidade.setText(JtProdutos.getValueAt(JtProdutos.getSelectedRow(), 2).toString());
            txtPreco.setText(JtProdutos.getValueAt(JtProdutos.getSelectedRow(), 3).toString());

        }

    }//GEN-LAST:event_JtProdutosMouseClicked

    private void JtProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtProdutosKeyReleased

        if(JtProdutos.getSelectedRow() != -1){
            txtNomedoProduto.setText(JtProdutos.getValueAt(JtProdutos.getSelectedRow(), 1).toString());
            txtQuantidade.setText(JtProdutos.getValueAt(JtProdutos.getSelectedRow(), 2).toString());
            txtPreco.setText(JtProdutos.getValueAt(JtProdutos.getSelectedRow(), 3).toString());

        }

    }//GEN-LAST:event_JtProdutosKeyReleased

    private void BotaoAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAlterarProdutoActionPerformed
        
        if (JtProdutos.getSelectedRow() != -1){
            JtProdutos.setValueAt(txtNomedoProduto.getText(), JtProdutos.getSelectedRow(), 1);
            JtProdutos.setValueAt(txtQuantidade.getText(), JtProdutos.getSelectedRow(), 2);
            JtProdutos.setValueAt(txtPreco.getText(), JtProdutos.getSelectedRow(), 3);
        }
        else{
            JOptionPane.showMessageDialog(null, "Produto não selecionado");
        }
        
        txtNomedoProduto.setText("");
        txtQuantidade.setText("");
        txtPreco.setText("");
         
    }//GEN-LAST:event_BotaoAlterarProdutoActionPerformed

    private void BotaoSalvarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarTabelaActionPerformed
            
        dispose();
        
    }//GEN-LAST:event_BotaoSalvarTabelaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAdicionarProduto;
    private javax.swing.JButton BotaoAlterarProduto;
    private javax.swing.JButton BotaoRemoverProduto;
    private javax.swing.JButton BotaoSalvarTabela;
    private javax.swing.JTable JtProdutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNomedoProduto;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
